# Generated by Django 3.1.7 on 2021-04-03 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.abituser')),
                ('language', models.CharField(choices=[('EN', 'english'), ('FR', 'french'), ('GE', 'german')], max_length=2, null=True)),
                ('citizenship', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='geography.country')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='applicants.applicant')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('middlename', models.CharField(blank=True, default='', max_length=255)),
                ('gender', models.CharField(choices=[('UN', 'UNKNOWN'), ('ML', 'MALE'), ('FM', 'FEMALE')], default='UN', max_length=2)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('no_address', models.BooleanField(default=False)),
                ('address', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='geography.address')),
            ],
        ),
        migrations.CreateModel(
            name='PreliminaryForm',
            fields=[
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preliminary_form', serialize=False, to='applicants.applicant')),
                ('need_dormitory', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EG', 'ege'), ('IN', 'internal exam')], max_length=2)),
                ('year', models.PositiveIntegerField()),
                ('mark', models.PositiveIntegerField(null=True)),
                ('subject', models.CharField(max_length=2)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='applicants.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('SC', 'school'), ('CL', 'college'), ('BA', 'bachelor'), ('SP', 'specialist'), ('MA', 'master')], max_length=2)),
                ('document_type', models.CharField(choices=[('CT', 'certificate'), ('DP', 'diploma')], max_length=2)),
                ('series', models.CharField(blank=True, default='', max_length=255)),
                ('number', models.CharField(blank=True, max_length=255)),
                ('issued_date', models.DateField(null=True)),
                ('name', models.CharField(max_length=2047)),
                ('year', models.PositiveIntegerField()),
                ('original', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='applicants.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='applicants.person')),
                ('series', models.CharField(blank=True, default='', max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('issuer', models.CharField(blank=True, default='', max_length=255)),
                ('issuer_code', models.CharField(blank=True, default='', max_length=255)),
                ('issued_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDataProcessingAgreement',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pd_agreement', serialize=False, to='applicants.person')),
                ('ip', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=2047)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='applicants.person')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_phones', to='applicants.person')),
            ],
        ),
    ]
