# Generated by Django 3.1.7 on 2021-04-03 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ref",
                    models.CharField(
                        db_index=True, default=None, max_length=2047, unique=True
                    ),
                ),
                ("mega_direction_number", models.CharField(default="1", max_length=2)),
                (
                    "mega_direction_name",
                    models.CharField(default="Авиастроение", max_length=255),
                ),
                ("name", models.CharField(default=None, max_length=255)),
                ("code", models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SelectedSpeciality",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_specialities",
                        to="applicants.applicant",
                    ),
                ),
                (
                    "speciality",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applicants.speciality",
                    ),
                ),
            ],
        ),
    ]
