# Generated by Django 3.1.7 on 2021-04-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_selectedspeciality_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
