# Generated by Django 3.2 on 2021-04-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_auto_20210405_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='ref',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
