# Generated by Django 3.2 on 2021-04-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0006_alter_applicant_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='system_code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
