# Generated by Django 3.2 on 2021-04-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MegaDirection',
            fields=[
                ('ref', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=15)),
                ('contact_information', models.CharField(blank=True, default='', max_length=2047)),
            ],
        ),
    ]
