# Generated by Django 3.1.7 on 2021-04-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, default='', max_length=2047)),
                ('district', models.CharField(blank=True, default='', max_length=2047)),
                ('city', models.CharField(blank=True, default='', max_length=2047)),
                ('township', models.CharField(blank=True, default='', max_length=2047)),
                ('zipcode', models.CharField(blank=True, default='', max_length=2047)),
                ('street', models.CharField(blank=True, default='', max_length=2047)),
                ('house', models.CharField(blank=True, default='', max_length=2047)),
                ('building', models.CharField(blank=True, default='', max_length=2047)),
                ('apartment', models.CharField(blank=True, default='', max_length=2047)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=7)),
                ('name', models.CharField(default=None, max_length=255)),
                ('ref', models.CharField(default=None, max_length=2047)),
            ],
        ),
    ]
